{
    'name': 'Hospital Management System',
    'version': '1.0',
    'summary': 'Manage hospital patients',
    'author': 'HMS',
    'license': 'LGPL-3',
    'depends': ['base', 'contacts'],
    'data': [
        'security/hms_security.xml',
        'security/hms_patient_rules.xml',
        'security/ir.model.access.csv',
        'views/hms_patient_views.xml',
        'views/hms_department_views.xml',
        'views/hms_doctors_views.xml',
        'views/res_partner_views.xml',
        'report/hms_patient_report.xml',
        'report/hms_patient_report_action.xml',
    ],
    'installable': True,
    'application': True,
}
